### ISSUE TITLE
Update Document

### ISSUE THREAD

**Issue by gelouko** [gelouko/nestjs-firestore#1]
Add the method `update` to the repository which will call Firestore's `update` method.

**Comment by maddy020** [comment]
Please assign this issue to me 
I have added the Firestore's update method and just going to create a PR

**Comment by gelouko** [comment]
Alright @maddy020 , thanks!

If you need help with something, let me know 

By the way, before you commit the code in your local repository, make sure you have `husky` set up:

```
npm install

npm run prepare
```

**Comment by maddy020** [comment]
I have already created a PR  and it has merged
